version: "3"
services:
  trafficcamnet-tao-toolkit:
    container_name: trafficcamnet-tao-toolkit
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/src
    working_dir: /app/src
    tty: true
